# Site settings
title: Jeff Bayes
header-img: img/home-bg.jpg
email: jbayes92@gmail.com
description: "The personal website and blog of Jeff Bayes. From Eugene, OR, currently in Seattle, WA. Software engineer, programmer, strength athlete, musician, trumpet player, student at University of Oregon."
baseurl: ""
url: "http://localhost:4000/"
twitter_username: jbayes92
facebook_username: jbayes92
github_username: jeffbayes
linkedin_username: jeffbayes

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
